export const catJson = [
    { id : '1' ,key : 'categoria-prima', name : 'Categoria Prima' , description : 'descrizione categoria'},
    { id : '2' ,key : 'categoria-prima2342', name : 'Categoria Seconda' , description : 'descrizione categoria'},
    { id : '3' ,key : 'categoria-prima34234', name : 'Categoria Terza' , description : 'descrizione categoria'},
    { id : '4' ,key : 'categoria-prima423423', name : 'Categoria Quarta' , description : 'descrizione categoria'},
];


export const postJson_1 = [
    { id : '45645645' ,key : 'post-uno', name : 'GraphQL ? Scopriamolo Insieme ! Pro e Contro di questa Tecnologia! [Dev 2019]' , description : 'GraphQL è un linguaggio di query per le API. GraphQL fornisce una descrizione completa e comprensibile dei dati nella tua API e offre ai clienti il ​​potere di chiedere esattamente ciò di cui hanno bisogno e nient’altro. GraphQL si spera che semplifichi l’evoluzione delle API. In questo post vedremo tutte le cose meravigliose su GraphQL oppure guarda il video sul mio canale. PRO:questi sono i vantaggi più evidenti Con una singola..' ,time : 'now', img : 'https://image.freepik.com/free-vector/abstract-design-background_1048-8430.jpg'},
    { id : '432425645645' ,key : 'post-trwe', name : 'Programmare Consigli v1.2' , description : 'E’ solo la passione che ti spinge ad andare avanti in questo mestiere o semplicemente tutto quello che dobbiamo studiare è dettato dal contesto lavorativo. Due nuovi video sul mondo dello sviluppo software.Qualche consiglio che mi sento di dare dalla mia esperienza a chi si affaccia a questo fantastico mondo. Versione 1.1 Version 1.2 ➤ Diventa un Donatore, supporta Isjeady…diventa il “mio Padrone” per accedere ai codici sorgenti dei tutorial..',time : '1 Minute',img : 'https://static.vecteezy.com/system/resources/previews/000/136/250/non_2x/rhinestone-abstract-background-vector.jpg'},
    { id : '42342345645645' ,key : 'post-ssdas', name : 'NPM Commands' , description : 'Elenco dei comandi NPM più utilizzati //Install everything in package.json npm install | npm i //clean cache npm cache clean //Install a package npm install axios //Update production packages npm updated //Update global packages npm updated -g //list packages npm list //check for outdated packages npm outdated //check your enviroments npm doctor //get help on npm npm help //create a package.json file npm init //manage package owner npm owner //search..',time : '2 Years', img : 'http://coremango.com/wp-content/uploads/2018/01/5458286-abstract-pictures.jpg'},
];

export const postJson_2 = [
    { id : '45645645' ,key : 'post-uno', name : 'GraphQL ? Scopriamolo Insieme ! Pro e Contro di questa Tecnologia! [Dev 2019]' , description : 'GraphQL è un linguaggio di query per le API. GraphQL fornisce una descrizione completa e comprensibile dei dati nella tua API e offre ai clienti il ​​potere di chiedere esattamente ciò di cui hanno bisogno e nient’altro. GraphQL si spera che semplifichi l’evoluzione delle API. In questo post vedremo tutte le cose meravigliose su GraphQL oppure guarda il video sul mio canale. PRO:questi sono i vantaggi più evidenti Con una singola..' ,time : 'now', img : 'https://image.freepik.com/free-vector/abstract-design-background_1048-8430.jpg'},
    { id : '432425645645' ,key : 'post-trwe', name : 'Programmare Consigli v1.2' , description : 'E’ solo la passione che ti spinge ad andare avanti in questo mestiere o semplicemente tutto quello che dobbiamo studiare è dettato dal contesto lavorativo. Due nuovi video sul mondo dello sviluppo software.Qualche consiglio che mi sento di dare dalla mia esperienza a chi si affaccia a questo fantastico mondo. Versione 1.1 Version 1.2 ➤ Diventa un Donatore, supporta Isjeady…diventa il “mio Padrone” per accedere ai codici sorgenti dei tutorial..',time : '1 Minute',img : 'https://static.vecteezy.com/system/resources/previews/000/136/250/non_2x/rhinestone-abstract-background-vector.jpg'},
    { id : '42342345645645' ,key : 'post-ssdas', name : 'NPM Commands' , description : 'Elenco dei comandi NPM più utilizzati //Install everything in package.json npm install | npm i //clean cache npm cache clean //Install a package npm install axios //Update production packages npm updated //Update global packages npm updated -g //list packages npm list //check for outdated packages npm outdated //check your enviroments npm doctor //get help on npm npm help //create a package.json file npm init //manage package owner npm owner //search..',time : '2 Years', img : 'http://coremango.com/wp-content/uploads/2018/01/5458286-abstract-pictures.jpg'},
];

export const postJson_3 = [
    { id : '45645645' ,key : 'post-uno', name : 'GraphQL ? Scopriamolo Insieme ! Pro e Contro di questa Tecnologia! [Dev 2019]' , description : 'GraphQL è un linguaggio di query per le API. GraphQL fornisce una descrizione completa e comprensibile dei dati nella tua API e offre ai clienti il ​​potere di chiedere esattamente ciò di cui hanno bisogno e nient’altro. GraphQL si spera che semplifichi l’evoluzione delle API. In questo post vedremo tutte le cose meravigliose su GraphQL oppure guarda il video sul mio canale. PRO:questi sono i vantaggi più evidenti Con una singola..' ,time : 'now', img : 'https://image.freepik.com/free-vector/abstract-design-background_1048-8430.jpg'},
    { id : '432425645645' ,key : 'post-trwe', name : 'Programmare Consigli v1.2' , description : 'E’ solo la passione che ti spinge ad andare avanti in questo mestiere o semplicemente tutto quello che dobbiamo studiare è dettato dal contesto lavorativo. Due nuovi video sul mondo dello sviluppo software.Qualche consiglio che mi sento di dare dalla mia esperienza a chi si affaccia a questo fantastico mondo. Versione 1.1 Version 1.2 ➤ Diventa un Donatore, supporta Isjeady…diventa il “mio Padrone” per accedere ai codici sorgenti dei tutorial..',time : '1 Minute',img : 'https://static.vecteezy.com/system/resources/previews/000/136/250/non_2x/rhinestone-abstract-background-vector.jpg'},
    { id : '42342345645645' ,key : 'post-ssdas', name : 'NPM Commands' , description : 'Elenco dei comandi NPM più utilizzati //Install everything in package.json npm install | npm i //clean cache npm cache clean //Install a package npm install axios //Update production packages npm updated //Update global packages npm updated -g //list packages npm list //check for outdated packages npm outdated //check your enviroments npm doctor //get help on npm npm help //create a package.json file npm init //manage package owner npm owner //search..',time : '2 Years', img : 'http://coremango.com/wp-content/uploads/2018/01/5458286-abstract-pictures.jpg'},
];
